[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
counter = "EDimXSJLG8u83mqyZJYtxrRFLQBaePexbYFtuw5ijBau"

[programs.devnet]
counter = "EDimXSJLG8u83mqyZJYtxrRFLQBaePexbYFtuw5ijBau"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/devdok/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
